# Generated by Django 3.1.4 on 2020-12-22 12:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Заметка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2020, 12, 22, 12, 53, 23, 144062, tzinfo=utc), verbose_name='Срок')),
                ('status', models.CharField(choices=[('active', 'активная'), ('expired', 'просроченная'), ('completed', 'выполненная'), ('archived', 'архивированная')], default='active', max_length=100, verbose_name='Статус')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('color', models.CharField(blank=True, choices=[('red', '#FF0000'), ('yellow', '#FFFF00'), ('blue', '#0000FF'), ('green', '#008000'), ('grey', '#808080'), ('aqua', '#00FFFF')], default=None, max_length=100, verbose_name='Цвет')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
