# Generated by Django 3.1.4 on 2020-12-24 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201223_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 24, 8, 30, 13, 810074, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'активная'), ('completed', 'выполненная'), ('archived', 'архивированная')], default='active', max_length=100, verbose_name='Статус'),
        ),
    ]
