# Generated by Django 3.1.4 on 2020-12-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201224_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='autor',
            new_name='author',
        ),
    ]
