# Generated by Django 3.1.4 on 2020-12-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20201224_1202'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique-title'),
        ),
    ]
