# Generated by Django 3.1.4 on 2021-01-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_task_description'),
    ]

    operations = [
        migrations.RenameModel('Tag', 'Project'),
    ]
