# Generated by Django 3.1.4 on 2021-01-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20210119_1441'),
    ]

    operations = [
        migrations.RenameField('Task', 'tag', 'project')
    ]
